### ISSUE TITLE
python 3.2.3安装出现如下问题

### ISSUE THREAD

**Issue by noline** [7sDream/zhihu-py3#59]
>>> from zhihu import ZhihuClient
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.2/dist-packages/zhihu/__init__.py", line 10, in <module>
    from .activity import Activity
  File "/usr/local/lib/python3.2/dist-packages/zhihu/activity.py", line 12, in <module>
    from .topic import Topic
  File "/usr/local/lib/python3.2/dist-packages/zhihu/topic.py", line 81
    yield Topic(Zhihu_URL + topic_tag['href'],
SyntaxError: 'return' with argument inside generator

大神们告诉我，怎么解决？

**Comment by 7sDream** [comment]
升级python。
=。=

**Comment by 7sDream** [comment]
经过分析发现是因为我们混用了 return 和 yield 造成的这个问题，这种语法在高版本 python 中是合法的，但是低版本不允许，我们会在0.3.6版本修复这个问题。你可以那时候再试试安装。
