### ISSUE TITLE
Ubuntu环境下git安装字符编码问题有误

### ISSUE THREAD

**Issue by Universeyi** [7sDream/zhihu-py3#79]
`root@iZ28dhz7tobZ:~/zhihu-py3# cd test/
root@iZ28dhz7tobZ:~/zhihu-py3/test# python3 zhihu-test.py
Test dir:  /root/zhihu-py3/test/test
Test dir not exist.
Cookies file found.
Making test dir...Done

===== test start =====
===== test failed =====
Cleaning...Done
Traceback (most recent call last):
  File "zhihu-test.py", line 869, in <module>
    raise e
  File "zhihu-test.py", line 863, in <module>
    'test()', setup='from __main__ import test', number=1)
  File "/root/anaconda3/lib/python3.5/timeit.py", line 213, in timeit
    return Timer(stmt, setup, timer, globals).timeit(number)
  File "/root/anaconda3/lib/python3.5/timeit.py", line 178, in timeit
    timing = self.inner(it, self.timer)
  File "<timeit-src>", line 6, in inner
  File "zhihu-test.py", line 813, in test
    test_question()
  File "zhihu-test.py", line 18, in test_question
    print(question.title)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-15: ordinal not in range(128)`

外部是否存在解决方法？

**Comment by arpit1997** [comment]
>Root @ iZ28dhz7tobZ:/ zhihu-Py3 the Test CD # / 
root @ iZ28dhz7tobZ:/ zhihu-Py3 / # for python3 zhihu-test.py the Test 
the Test the dir: / root / zhihu-Py3 / the Test / the Test 
the Test the dir Not the exist. 
Cookies File found. 
Making the Test the Done the dir ...
Start te Test ===== ===== 
===== ===== the Test failed The 
Cleaning ... the Done 
Traceback (MOST Recent Last Call): 
File "zhihu-test.py", Line 869, in 
E The raise 
File "zhihu-test.py", Line 863, in 
'the Test ()', = Setup 'from main Import the Test', Number = 1) 
File "/root/anaconda3/lib/python3.5/timeit.py ", Line 213, in the timeit 
return the Timer (stmt of the, Setup, Timer, Globals) .timeit (Number) 
File" /root/anaconda3/lib/python3.5/timeit.py ", Line 178, in the timeit 
the Timing = Self. Inner (IT, self.timer) 
File "", Line. 6, in Inner 
File "zhihu-test.py", Line 813, in the Test 
test_question () 
File "zhihu-test.py", Line 18, in test_question 
Print ( Questions in) 
UnicodeEncodeError: 'ASCII' CODEC CAN Not the encode characters in position 0-15: ORDINAL Not in the Range (128)

I guess the problem is at system level
