### ISSUE TITLE
在topic.hot_questions與topic.questions下面一直出現Error

### ISSUE THREAD

**Issue by JennChao** [7sDream/zhihu-py3#88]
你好

以下是我的code與error的內容
想請你看一下是哪裡出了問題
謝謝你

--------------------------------------------------------------------------------------------------
Code:
topic_travel_in_Taiwan = client.topic('http://www.zhihu.com/topic/19755487')
questions_in_topic = topic_travel_in_Taiwan.questions
first_q = next(questions_in_topic)

出現error如下
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/zhihu/topic.py", line 293, in questions
    older_time_stamp = int(questions[-1].h2.span['data-timestamp'])
IndexError: list index out of range

--------------------------------------------------------------------------------------------------

Code:
hot_questions = topic_travel_in_Taiwan.hot_questions
next(hot_questions)

出現過兩個不同的error

1. 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/zhihu/topic.py", line 386, in hot_questions
    params = {'start': 0, '_xsrf': self.xsrf}
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/zhihu/common.py", line 100, in wrapper
    value = func(self)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/zhihu/topic.py", line 45, in xsrf
    return self.soup.find('input', attrs={'name': '_xsrf'})['value']
TypeError: 'NoneType' object is not subscriptable

2. 
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/zhihu/topic.py", line 473, in _get_score
    _ = h2['class']
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/bs4/element.py", line 997, in __getitem__
    return self.attrs[key]
KeyError: 'class'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/zhihu/topic.py", line 396, in hot_questions
    questions.sort(key=self._get_score, reverse=True)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/zhihu/topic.py", line 476, in _get_score
    return div.parent.parent['data-score']
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/bs4/element.py", line 997, in __getitem__
    return self.attrs[key]
KeyError: 'data-score'

**Comment by 7sDream** [comment]
因为这个项目是分析知乎前端的，然而知乎的前端 HTML 代码最近在疯狂变化。
而且我现在在公司实习，平常的空闲时间很少已经没法花大量经历以维护个人项目了。

如果可能的话你可以试试我新的那个 zhihu_oauth 项目，那个是分析知乎的 Android API 的，基本不会出错，而且代码也比这个规范和优雅，因为传输的是 JSON， 比 HTML 版本的也要快很多。

接口和这个项目基本一样，看看文档就会了~

https://github.com/7sDream/zhihu-oauth

**Comment by thekoc** [comment]
@7sDream 
但是那个项目好像没有这个接口……
