### ISSUE TITLE
测试报错：不支持 beauifulsoup4 最新版4.4.0

### ISSUE THREAD

**Issue by jiaqiluo** [7sDream/zhihu-py3#9]
System: Mac OSX Yosemite 10.10.4
```
<zhihu.Answer object at 0x1030a5e48>
<generator object top_i_answers at 0x105553510>
<generator object answers at 0x105553510>
Traceback (most recent call last):
  File "zhihu-test.py", line 267, in <module>
    test_question()
  File "zhihu-test.py", line 48, in test_question
    for answer in question.answers:
  File "/Users/jiaqiluo/Documents/python_learning/zhihu-py3-master/zhihu.py", line 376, in answers
    _xsrf = self.soup.find('input', attrs={'name': '_xsrf'})['value']
TypeError: 'NoneType' object is not subscriptable
```
我刚刚开始学习python，可能这个问题比较低级，我也在积极寻找解决方法，但是还是希望作者（或其他人）帮助解决。

谢谢

**Comment by 7sDream** [comment]
那个 你生成了Cookies文件的不？ 如果是生成了之后报的错有可能是知乎改Html了。

**Comment by 7sDream** [comment]
我现在不在家 下午去帮忙看看。

**Comment by jiaqiluo** [comment]
Cookies 文件已经生成，而且可以工作。 
运行效果如下：
```
host-121-88:zhihu-py3-master jiaqiluo$ python3 zhihu-test.py 
/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/bs4/__init__.py:166: UserWarning: No parser was explicitly specified, so I'm using the best available HTML parser for this system ("html.parser"). This usually isn't a problem, but if you run this code on another system, or in a different virtual environment, it may use a different parser and behave differently.

To get rid of this warning, change this:

 BeautifulSoup([your markup])

to this:

 BeautifulSoup([your markup], "html.parser")

  markup_type=markup_type))
关系亲密的人之间要说「谢谢」吗？
从小父母和大家庭里，长辈都教我们得到别人帮助时要说“谢谢”。比方说家庭聚餐，亲人们帮忙夹了菜要感谢。无论多么亲密,父母还是兄妹，都要说声谢谢。   后来上了高中，大学。也习惯性的及时表达对他人帮助的感谢。  但室友们，还有男朋友，都不喜欢我这样。他们说，这样说的话会感觉双方很有距离感很生疏。尤其是男朋友，不喜欢我这样，他说这样很不亲密，情侣之间就不分得那么清，不需要谢谢的。但我从小习惯了，别人帮了我我不说的话，会很不自在。  怎么办？我还要继续这样吗？什么时候不该说"谢谢”？？
630
4312
['心理学', '恋爱', '社会', '礼仪', '亲密关系']
<zhihu.Answer object at 0x1030a7d30>
<generator object top_i_answers at 0x10555bc60>
<generator object answers at 0x10555bc60>
Traceback (most recent call last):
  File "zhihu-test.py", line 267, in <module>
    test_question()
  File "zhihu-test.py", line 48, in test_question
    for answer in question.answers:
  File "/Users/jiaqiluo/Documents/python_learning/zhihu-py3-master/zhihu.py", line 376, in answers
    _xsrf = self.soup.find('input', attrs={'name': '_xsrf'})['value']
TypeError: 'NoneType' object is not subscriptable
```

**Comment by 7sDream** [comment]
我回家又跑了一遍test并没有什么问题来着。我这里没法复现的话就比较难找到问题呢。

这样，你在登录了知乎的情况下打开[这个网页](http://www.zhihu.com/question/24825703)

然后在网页源代码里找找有没有这样一行（value值可以不同）：

```html
<input type="hidden" value="be7a146a19fe090519e608ebdd4598xx" name="_xsrf">
```

如果没有的话，可能Mac系统下Python的html paser找不到这个元素？感觉可能性很低啊……

不管怎么样你先试着找找这行吧。

**Comment by jiaqiluo** [comment]
找到代码如下：
```javascript
<input type="hidden" name="_xsrf" value="88e556e13af8f9b54d379f64efffebcf">
```
name 和 value 的顺序和你的不一样，是这个原因导致不工作吗？

**Comment by buzouxun** [comment]
我觉得和顺序没有关系，我也run了一下zhihu-test.py，在我win电脑上没问题。
我的beautifulsoup4的version 是4.3.2。
有一些debug建议，可以在这行出问题的代码前(上)面
```python
_xsrf = self.soup.find('input', attrs={'name': '_xsrf'})['value']
```
加上
```python
    if self == None:
	    print("S")
    if self.soup == None:
	    print("A")
    if self.soup.find('input', attrs={'name': '_xsrf'}) == None:
	    print("B")
    if self.soup.find('input', attrs={'name': '_xsrf'})['value'] == None:
	    print("C")
```
你也可以加上自己的if条件和print值。
然后回来告诉，print发生了什么?

**Comment by jiaqiluo** [comment]
返回 B
测试结果如下：
```python
/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/bs4/__init__.py:166: UserWarning: No parser was explicitly specified, so I'm using the best available HTML parser for this system ("html.parser"). This usually isn't a problem, but if you run this code on another system, or in a different virtual environment, it may use a different parser and behave differently.

To get rid of this warning, change this:

 BeautifulSoup([your markup])

to this:

 BeautifulSoup([your markup], "html.parser")

  markup_type=markup_type))
关系亲密的人之间要说「谢谢」吗？
从小父母和大家庭里，长辈都教我们得到别人帮助时要说“谢谢”。比方说家庭聚餐，亲人们帮忙夹了菜要感谢。无论多么亲密,父母还是兄妹，都要说声谢谢。   后来上了高中，大学。也习惯性的及时表达对他人帮助的感谢。  但室友们，还有男朋友，都不喜欢我这样。他们说，这样说的话会感觉双方很有距离感很生疏。尤其是男朋友，不喜欢我这样，他说这样很不亲密，情侣之间就不分得那么清，不需要谢谢的。但我从小习惯了，别人帮了我我不说的话，会很不自在。  怎么办？我还要继续这样吗？什么时候不该说"谢谢”？？
630
4313
['心理学', '恋爱', '社会', '礼仪', '亲密关系']
<zhihu.Answer object at 0x1030c6048>
<generator object top_i_answers at 0x105590438>
<generator object answers at 0x105590438>
B
Traceback (most recent call last):
  File "zhihu-test.py", line 267, in <module>
    test_question()
  File "zhihu-test.py", line 48, in test_question
    for answer in question.answers:
  File "/Users/jiaqiluo/Documents/python_learning/zhihu-py3-master/zhihu.py", line 383, in answers
    if self.soup.find('input', attrs={'name': '_xsrf'})['value'] == None:
TypeError: 'NoneType' object is not subscriptable
```

**Comment by buzouxun** [comment]
然后你可以再加入一行print。比如
```python
if self.soup.find('input', attrs={'name': '_xsrf'}) == None:
        print(self.soup)
        print("B")
```
看看到底print出来什么

--------------------------------------

我自己的`print(self.soup)`出来的是这个样子的: (省略中间没有用的by ... ...)
```
<!DOCTYPE html>

<html class="no-js" dropeffect="none" lang="zh-CN">
<head>
<meta charset="utf-8"/>
<meta content="IE=edge,chrome=1" http-equiv="X-UA-Compatible"/>
<meta content="webkit" name="renderer"/>
<title>

关系亲密的人之间要说「谢谢」吗？ - 知乎

</title>

... ...

<script class="json-inline" data-name="current_user" type="text/json">["Zhu Junyu","zhu-junyu","http:\/\/pic2.zhimg.com\/45c4aae941c8797957735b5c9841c1e1_s.jpg","e087059c5f342fca4b9f2e20ba948245","Impossible is nothing",0,0,1,"zjyhou@126.com","http:\/\/www.126.com",0,true,false,56946581307392]</script>
<script class="json-inline" data-name="env" type="text/json">["zhihu.com","comet.zhihu.com",false,null]</script>
<script class="json-inline" data-name="permissions" type="text/json">[]</script>
<script class="json-inline" data-name="ga_vars" type="text/json">{"user_created":1406344655000,"now":1437426985000,"abtest_mask":"---------1--------------------","user_attr":[1,0,0,"-",1],"user_hash":"e087059c5f342fca4b9f2e20ba948245"}</script>
<script class="json-inline" data-name="current_question" type="text/json">{"status":"normal","isLocked":0,"detailEditReasonRequired":true,"editPermission":false,"isAnon":0,"qid":2112271,"urlToken":24825703,"showInvitePanel":false,"askAboutMember":0}</script>
<script class="json-inline" data-name="current_question_owner" type="text/json">false</script>
<script class="json-inline" data-name="draft" type="text/json">[]</script>
<script class="json-inline" data-name="my_answer" type="text/json">{}</script>
<script class="json-inline" data-name="redirect_to" type="text/json">""</script>
<script src="http://static.zhihu.com/static/ver/e81122a3ca2b78ad911aff474211d7c3.extern_src.min.js"></script>
<script src="http://static.zhihu.com/static/ver/7903291d85a43e770aad31f43b47dd80.app_core.js"></script>
<script src="http://static.zhihu.com/static/ver/e7de8cc567e19d0e45bb2bbc85a1c5f3.sign.js"></script>
<script src="http://static.zhihu.com/static/ver/af108dec0754c34a045cd6f5b101de4a.app.js"></script>
<script src="http://static.zhihu.com/static/ver/f49cc92277b8615088d28528009361aa.rich_text_editor.js"></script>
<script type="text/zscript" znonce="bd6e06c1bdf54ca1820565d72f67f634">
ZH.entrySQ();
</script>
<input name="_xsrf" type="hidden" value="9c891fd27f7581328a9d01dc6b292fa7"/>
</body>
</html>
```
我的print出来的倒数第3行是有`<input name="_xsrf" type="hidden" value="9c891fd27f7581328a9d01dc6b292fa7"/>`，不知道你的有没有？

如果有的话，`self.soup.find('input', attrs={'name': '_xsrf'})`就不应该等于 `None`。

**Comment by jiaqiluo** [comment]
我加入了你说的code：
```python
if self.soup.find('input', attrs={'name': '_xsrf'}) == None:
        print(self.soup)
        print("B")
```
得到如下和你相同的结果：
```python
<!DOCTYPE html>

<html class="no-js" dropeffect="none" lang="zh-CN">
<head>
<meta charset="utf-8"/>
<meta content="IE=edge,chrome=1" http-equiv="X-UA-Compatible"/>
<meta content="webkit" name="renderer"/>
<title>

关系亲密的人之间要说「谢谢」吗？ - 知乎

</title>

... ...
... ...

</script>
<input name="_xsrf" type="hidden" value="e2c8c0ac09c62e1b2716f049874d2e4f"/>
</body>
</html>
B
```
看来 self.soup != None,  好奇怪。

**Comment by buzouxun** [comment]
@jiaqiluo  print的结果不应该是`B C`，应该只是`B`。不会打印`C`的原因是程序没有run到`print("C")`这一行。换句话说，程序在`print("C")`的上一行就已经出错了然后停止了。

回到你的测试报错，我觉得有可能是 bs4 有问题。因为我 run 我自己的 code 的时候，并没有看到这些提示：
```
To get rid of this warning, change this:

 BeautifulSoup([your markup])

to this:

 BeautifulSoup([your markup], "html.parser")

  markup_type=markup_type))
```

像我之前说的，我的 beautifulsoup4 的 version 是4.3.2。 你看看你的 beautifulsoup4 / bs4 的 version。应该是打开`/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/bs4/__init__.py`里面有的。如果你的 version 和我的不一样，可以试试换个bs4，看一看

如果你完成上面的步骤，确定bs4这个 package 没问题，我能想到的你还能做的，就是 run 其他的 tests 试试看。 我的意思是在`zhihu-test.py`里面:
```python
#test_question()
test_answer()
test_author()
test_collection()
test_book()
test_article()
```

看看其他的会不会出同样的错

**Comment by jiaqiluo** [comment]
问题解决！
我重新安装了 beautifulsoup4 4.3.2, 测试成功。
－－－－－－－－－
提示:
```python
pip install beautifulsoup4
```
只能安装最新版本。
请卸载最新版本，然后用如下方法安装 beautifulsoup4 4.3.2
```python
pip install http://www.crummy.com/software/BeautifulSoup/bs4/download/4.3/beautifulsoup4-4.3.2.tar.gz
```

**Comment by 7sDream** [comment]
@jiaqiluo 
我修复了一下，你重新pull一下，然后安装最新版的bs4，过一test遍测试下吧。

记得来反馈，Thanks。

**Comment by 7sDream** [comment]
关 Issue啦。

@jiaqiluo 如果有反馈的话请加QQ群：478786205
