### ISSUE TITLE
用户id太长时，会报错

### ISSUE THREAD

**Issue by whhsw** [7sDream/zhihu-py3#91]
user = client.from_url(v.profileUrl)
print (user.follower_count)

Traceback (most recent call last):
  File "zhihu.py", line 70, in <module>
    process()
  File "zhihu.py", line 63, in process
    print (user.follower_count)
  File "Env/codelab/lib/python2.7/site-packages/zhihu_oauth/zhcls/normal.py", line 59, in wrapper
    self._get_data()
  File "Env/codelab/lib/python2.7/site-packages/zhihu_oauth/zhcls/base.py", line 75, in _get_data
    raise e
zhihu_oauth.exception.GetDataErrorException

example: 
https://www.zhihu.com/people/meng-meng-meng-meng-meng-meng-meng-duo-nuo

具体是什么原因没仔细看，不过看起来只要https://www.zhihu.com/people/<userid>, 这个userid超过了一定的长度，就报错..

**Comment by whhsw** [comment]
figured out. should use 'hash' other than 'profile slug' when the slug is very long
